// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-AJiQYNJcKsnk7WPz1gQBtWVZmx9ZlUY',
    appId: '1:577223627494:web:e231abfc216e82fac5e127',
    messagingSenderId: '577223627494',
    projectId: 'grand-flutter-project-mywrit',
    authDomain: 'grand-flutter-project-mywrit.firebaseapp.com',
    storageBucket: 'grand-flutter-project-mywrit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCqPjFeaOHNi6JZWQ1cYetCGIKUebSeQA',
    appId: '1:577223627494:android:3a88ca4ba1036159c5e127',
    messagingSenderId: '577223627494',
    projectId: 'grand-flutter-project-mywrit',
    storageBucket: 'grand-flutter-project-mywrit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCagTCjRLMEFumpnWg8p_QjDInGyiMQyBI',
    appId: '1:577223627494:ios:9c69b1e6d96face3c5e127',
    messagingSenderId: '577223627494',
    projectId: 'grand-flutter-project-mywrit',
    storageBucket: 'grand-flutter-project-mywrit.appspot.com',
    iosBundleId: 'com.example.tuto',
  );
}
